/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-11-22 05:52:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jQuery_002dTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_005fTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/hyun/js/AjaxModule.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tfunction show() {\r\n");
      out.write("\t\tvar p1 = document.all.p1;\r\n");
      out.write("\t\t//alert(p1.innerHTML);\r\n");
      out.write("\t\tp1.innerHTML = '<font color=\"blue\">앗앗앗</font>';\r\n");
      out.write("\t\tvar text = document.fm.text.value;\r\n");
      out.write("\t\tvar param = 'text=' + text;\r\n");
      out.write("\t\tsendRequest('ajax.do', param, showResult, 'GET');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showResult() {\r\n");
      out.write("\t\tif (httpRequest.readyState == 4) {\r\n");
      out.write("\t\t\tif (httpRequest.status == 200) {\r\n");
      out.write("\t\t\t\tvar data = httpRequest.responseText;\r\n");
      out.write("\t\t\t\tvar div = document.all.newNotice;\r\n");
      out.write("\t\t\t\tdiv.innerHTML = data;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showResult2() {\r\n");
      out.write("\t\tif (httpRequest.readyState == 4) {\r\n");
      out.write("\t\t\tif (httpRequest.status == 200) {\r\n");
      out.write("\t\t\t\tvar data = httpRequest.responseText;\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\tvar div = document.all.test;\r\n");
      out.write("\t\t\t\tdiv.innerHTML = data;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction show2() {\r\n");
      out.write("\t\tsendRequest('notice.do', null, showResult, 'GET');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction show3() {\r\n");
      out.write("\t\tsendRequest('test.do', null, showResult2, 'GET');\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\ttimeDisplay();\r\n");
      out.write("\r\n");
      out.write("\t\t$('.testr').click(function(){\r\n");
      out.write("\t\t\t$('#test').html('');\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'notice.do',\r\n");
      out.write("                dataType:'html',\r\n");
      out.write("                type:'GET',\r\n");
      out.write("                data:null,\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                    $('#test').html(data);\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#notice').click(show2);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction timeDisplay() {\r\n");
      out.write("\t\tdocument.all.timer.innerHTML = new Date().getSeconds();\r\n");
      out.write("\t\twindow.setTimeout('timeDisplay()', 1000);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>Notice</h2>\r\n");
      out.write("\t<div id=\"test\"></div>\r\n");
      out.write("\t<input type=\"button\" class=\"testr\" value=\"test\">\r\n");
      out.write("\t<div id=\"newNotice\"></div>\r\n");
      out.write("\t<input type=\"button\" id=\"notice\" value=\"notice\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<span id=\"timer\"></span> time\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<form name=\"fm\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"text\">\r\n");
      out.write("\t\t<p id=\"p1\">\r\n");
      out.write("\t\t\t<b>ajax</b><br> <font color=\"red\">????????</font>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<input type=\"button\" value=\"ajax\" id=\"ajax_test\" onclick=\"show()\">\r\n");
      out.write("\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
