/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-11-22 10:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jQuery_002dTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_005fTest2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/hyun/js/AjaxModule.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\twindow.onload=function(){\r\n");
      out.write("\t\t/* var rootNode=document.documentElement;\r\n");
      out.write("\t\talert(rootNode.nodeName);\r\n");
      out.write("\t\tvar bodyNode=rootNode.lastChild;\r\n");
      out.write("\t\talert(bodyNode.nodeName);\r\n");
      out.write("\t\tvar spanNode=bodyNode.firstChild.nextSibling;\r\n");
      out.write("\t\talert(spanNode.nodeName);\r\n");
      out.write("\t\tvar spanTextNode=spanNode.lastChild;\r\n");
      out.write("\t\talert(spanTextNode.nodeName); \r\n");
      out.write("\t\tvar spanNode3=document.getElementById('c');\r\n");
      out.write("\t\talert(spanNode3.nodeName);\r\n");
      out.write("\t\tvar spanTest3=spanNode3.lastChild;\r\n");
      out.write("\t\talert(spanTest3.nodeName); */\r\n");
      out.write("\t\tvar fontNode=document.getElementById('fn');\r\n");
      out.write("\t\tfontNode.setAttribute('color','blue');\r\n");
      out.write("\t\tfontNode.setAttribute('color','red');\r\n");
      out.write("\t\tfontNode.removeAttribute('color');\r\n");
      out.write("\t\tvar newSpan=document.createElement('span');\r\n");
      out.write("\t\tvar newSpanText=document.createTextNode('newSpan!');\r\n");
      out.write("\t\tnewSpan.setAttribute('id','b');\r\n");
      out.write("\t\tnewSpan.appendChild(newSpanText);\r\n");
      out.write("\t\tvar spanNode=document.getElementById('a');\r\n");
      out.write("\t\tspanNode.appendChild(newSpan);\r\n");
      out.write("\t\tvar count=0; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".addb\").click(function(){\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t\tvar newItem=document.createElement('div');\r\n");
      out.write("\t\t\tnewItem.setAttribute('id','item_'+count);\r\n");
      out.write("\t\t\tnewItem.innerHTML=\"새롭게추가된 아이템[\"+count+\"]<input type='button' class='remove' value='삭제'>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar itemList=document.getElementById('itemList');\r\n");
      out.write("\t\t\titemList.appendChild(newItem);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".remove\").click(function(e){\r\n");
      out.write("\t\t\talert('asd');\r\n");
      out.write("\t\t\tvar item=document.getElementById('item_'+e.count);\r\n");
      out.write("\t\t\talert(itme);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<span id=\"a\">spanA</span>\r\n");
      out.write("\t<p>Ajax<span id=\"b\">spanB</span></p>\r\n");
      out.write("\t<div><p>p</p><span id=\"c\">spanC</span></div>\r\n");
      out.write("\t<font id=\"fn\">asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasd</font>\r\n");
      out.write("\t<form>form</form>\r\n");
      out.write("\t<input type=\"button\" class=\"addb\" value=\"추가\">\r\n");
      out.write("\t<p id=\"itemList\"></p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
