/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-14 08:22:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Displaying text directions with <code>setPanel()</code></title>\r\n");
      out.write("    <style>\r\n");
      out.write("      /* Always set the map height explicitly to define the size of the div\r\n");
      out.write("       * element that contains the map. */\r\n");
      out.write("      #map {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      /* Optional: Makes the sample page fill the window. */\r\n");
      out.write("      html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("      #floating-panel {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 10px;\r\n");
      out.write("        left: 25%;\r\n");
      out.write("        z-index: 5;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        border: 1px solid #999;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-family: 'Roboto','sans-serif';\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      #right-panel {\r\n");
      out.write("        font-family: 'Roboto','sans-serif';\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #right-panel select, #right-panel input {\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #right-panel select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #right-panel i {\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("      }\r\n");
      out.write("      #right-panel {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: right;\r\n");
      out.write("        width: 390px;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("      }\r\n");
      out.write("      #map {\r\n");
      out.write("        margin-right: 400px;\r\n");
      out.write("      }\r\n");
      out.write("      #floating-panel {\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-family: Arial;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        box-shadow: 0 2px 2px rgba(33, 33, 33, 0.4);\r\n");
      out.write("        display: none;\r\n");
      out.write("      }\r\n");
      out.write("      @media print {\r\n");
      out.write("        #map {\r\n");
      out.write("          height: 500px;\r\n");
      out.write("          margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        #right-panel {\r\n");
      out.write("          float: none;\r\n");
      out.write("          width: auto;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"floating-panel\">\r\n");
      out.write("      <strong>Start:</strong>\r\n");
      out.write("      <select id=\"start\">\r\n");
      out.write("        <option value=\"chicago, il\">Chicago</option>\r\n");
      out.write("        <option value=\"st louis, mo\">St Louis</option>\r\n");
      out.write("        <option value=\"joplin, mo\">Joplin, MO</option>\r\n");
      out.write("        <option value=\"oklahoma city, ok\">Oklahoma City</option>\r\n");
      out.write("        <option value=\"amarillo, tx\">Amarillo</option>\r\n");
      out.write("        <option value=\"gallup, nm\">Gallup, NM</option>\r\n");
      out.write("        <option value=\"flagstaff, az\">Flagstaff, AZ</option>\r\n");
      out.write("        <option value=\"winona, az\">Winona</option>\r\n");
      out.write("        <option value=\"kingman, az\">Kingman</option>\r\n");
      out.write("        <option value=\"barstow, ca\">Barstow</option>\r\n");
      out.write("        <option value=\"san bernardino, ca\">San Bernardino</option>\r\n");
      out.write("        <option value=\"los angeles, ca\">Los Angeles</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <br>\r\n");
      out.write("      <strong>End:</strong>\r\n");
      out.write("      <select id=\"end\">\r\n");
      out.write("        <option value=\"chicago, il\">Chicago</option>\r\n");
      out.write("        <option value=\"st louis, mo\">St Louis</option>\r\n");
      out.write("        <option value=\"joplin, mo\">Joplin, MO</option>\r\n");
      out.write("        <option value=\"oklahoma city, ok\">Oklahoma City</option>\r\n");
      out.write("        <option value=\"amarillo, tx\">Amarillo</option>\r\n");
      out.write("        <option value=\"gallup, nm\">Gallup, NM</option>\r\n");
      out.write("        <option value=\"flagstaff, az\">Flagstaff, AZ</option>\r\n");
      out.write("        <option value=\"winona, az\">Winona</option>\r\n");
      out.write("        <option value=\"kingman, az\">Kingman</option>\r\n");
      out.write("        <option value=\"barstow, ca\">Barstow</option>\r\n");
      out.write("        <option value=\"san bernardino, ca\">San Bernardino</option>\r\n");
      out.write("        <option value=\"los angeles, ca\">Los Angeles</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"right-panel\"></div>\r\n");
      out.write("    <div id=\"map\"></div>\r\n");
      out.write("    <script>\r\n");
      out.write("      function initMap() {\r\n");
      out.write("        var directionsDisplay = new google.maps.DirectionsRenderer;\r\n");
      out.write("        var directionsService = new google.maps.DirectionsService;\r\n");
      out.write("        var map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("          zoom: 7,\r\n");
      out.write("          center: {lat: 41.85, lng: -87.65}\r\n");
      out.write("        });\r\n");
      out.write("        directionsDisplay.setMap(map);\r\n");
      out.write("        directionsDisplay.setPanel(document.getElementById('right-panel'));\r\n");
      out.write("\r\n");
      out.write("        var control = document.getElementById('floating-panel');\r\n");
      out.write("        control.style.display = 'block';\r\n");
      out.write("        map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);\r\n");
      out.write("\r\n");
      out.write("        var onChangeHandler = function() {\r\n");
      out.write("          calculateAndDisplayRoute(directionsService, directionsDisplay);\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById('start').addEventListener('change', onChangeHandler);\r\n");
      out.write("        document.getElementById('end').addEventListener('change', onChangeHandler);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function calculateAndDisplayRoute(directionsService, directionsDisplay) {\r\n");
      out.write("        var start = document.getElementById('start').value;\r\n");
      out.write("        var end = document.getElementById('end').value;\r\n");
      out.write("        directionsService.route({\r\n");
      out.write("          origin: start,\r\n");
      out.write("          destination: end,\r\n");
      out.write("          travelMode: 'DRIVING'\r\n");
      out.write("        }, function(response, status) {\r\n");
      out.write("          if (status === 'OK') {\r\n");
      out.write("            directionsDisplay.setDirections(response);\r\n");
      out.write("          } else {\r\n");
      out.write("            window.alert('Directions request failed due to ' + status);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script async defer\r\n");
      out.write("    src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDm4locFJLs9GfPhTFuk-mAZpcc_WyZOf4&callback=initMap\">\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
