/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-18 12:05:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"/finaltp/css/layerPopup.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"/finaltp/js/mypagelayer.js\"></script>\r\n");
      out.write("<script src=\"/finaltp/js/AjaxModule.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   window.onload = function() {\r\n");
      out.write("\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("         $('.openMask').click(function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            var string=$('#pfimg').attr('src');\r\n");
      out.write("            var arr=string.split(\"\\\\\");\r\n");
      out.write("            var buttonWrap=document.getElementById('buttonWrap');\r\n");
      out.write("            buttonWrap.setAttribute('style','background-image:url(\"'+arr[0]+'/'+arr[1]+'\");');\r\n");
      out.write("            wrapWindowByMask();\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   function show() {\r\n");
      out.write("      sendRequest('myWriting.do', 'w_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', showResult, 'GET');\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function show2() {\r\n");
      out.write("      sendRequest('myAccWriting.do', 'w_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', showResult,\r\n");
      out.write("            'GET');\r\n");
      out.write("   }\r\n");
      out.write("   function showplan() {\r\n");
      out.write("      sendRequest('mypage.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', 'w_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', null,\r\n");
      out.write("            'GET');\r\n");
      out.write("   }\r\n");
      out.write("   function showfollowing() {\r\n");
      out.write("      sendRequest('myFollowing.do', null, showResult, 'GET');\r\n");
      out.write("   }\r\n");
      out.write("   function showfollower() {\r\n");
      out.write("      sendRequest('myFollower.do', null, showResult, 'GET');\r\n");
      out.write("   }\r\n");
      out.write("   function showResult() {\r\n");
      out.write("      console.log(httpRequest.readyState);\r\n");
      out.write("      if (httpRequest.readyState == 4) {\r\n");
      out.write("         console.log(httpRequest.status);\r\n");
      out.write("         if (httpRequest.status == 200) {\r\n");
      out.write("            var data = httpRequest.responseText;\r\n");
      out.write("            var scripttest = document.getElementById('mypageContent');\r\n");
      out.write("            /* scripttest.setAttribute(\"style\", \"display: block;\"); */\r\n");
      out.write("            scripttest.innerHTML = data;\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   function imageURL(input) {\r\n");
      out.write("         \r\n");
      out.write("       if (input.files && input.files[0]) {\r\n");
      out.write("           var reader = new FileReader();\r\n");
      out.write("           reader.onload = function(e) {\r\n");
      out.write("              document.getElementsByClassName('buttonWrap')[0].setAttribute('style','background-image: url('+e.target.result+');')\r\n");
      out.write("           }\r\n");
      out.write("          reader.readAsDataURL(input.files[0]);\r\n");
      out.write("       }\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .buttonWrap {\r\n");
      out.write("        position:relative;\r\n");
      out.write("        float:left;\r\n");
      out.write("        overflow:hidden;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("        \r\n");
      out.write("        width:150px;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        background-size:150px 200px;\r\n");
      out.write("    }\r\n");
      out.write("    #preview {\r\n");
      out.write("        position：absolute;\r\n");
      out.write("        margin-left:-10px;\r\n");
      out.write("        filter:alpha(opacity=0);\r\n");
      out.write("        opacity:0;\r\n");
      out.write("        -moz-opacity:0;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("        width:150px;\r\n");
      out.write("        height:200px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      <div id=\"mask\"></div>\r\n");
      out.write("      <form name=\"edit\" action=\"memberEdit.do\" method=\"post\"  enctype=\"Multipart/form-data\">\r\n");
      out.write("         <div class=\"window\" id=\"window\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("            <p align=\"right\">\r\n");
      out.write("               <input class=\"close\" type=\"button\" value=\"X\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p align=\"center\" class=\"buttonWrap\" id=\"buttonWrap\">\r\n");
      out.write("               <input type=\"file\" name=\"file\" onchange=\"imageURL(this)\" id=\"preview\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p align=\"center\">\r\n");
      out.write("               <input type=\"password\" name=\"ppwd\" id=\"ppwd\" placeholder=\"현재 비밀번호\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p align=\"center\">\r\n");
      out.write("               <input type=\"password\" name=\"npwd\" id=\"npwd\" placeholder=\"변경 할 비밀번호\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p align=\"center\">\r\n");
      out.write("               <input type=\"password\" name=\"npwd2\" id=\"npwd2\" placeholder=\"변경 할 비밀번호 확인\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p align=\"center\">\r\n");
      out.write("               <input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      <table width=\"800\" align=\"center\" height=\"800\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td width=\"300\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td><table border=\"1\" cellspacing=\"0\" width=\"220\"\r\n");
      out.write("                                    height=\"400\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <td align=\"center\" height=\"230\">\r\n");
      out.write("                                             <img id=\"pfimg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.profile_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" width=\"80\" height=\"100\">\r\n");
      out.write("                                          \r\n");
      out.write("                                       \r\n");
      out.write("                                          <br> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <td align=\"center\" height=\"70\"><input type=\"button\"\r\n");
      out.write("                                          value=\"팔로워\" onclick=\"showfollower()\"><input type=\"button\" value=\"팔로잉\" onclick=\"javascript:showfollowing()\"><br>\r\n");
      out.write("                                          <a href=\"#\" class=\"openMask\">회원 정보 수정</a> / <a\r\n");
      out.write("                                          href=\"memberoutForm.do\">회원 탈퇴</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                 </table></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td><table border=\"1\" cellspacing=\"0\" width=\"220\"\r\n");
      out.write("                                    height=\"160\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <td align=\"center\"><a href=\"mypage.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"myPlanner\">MY\r\n");
      out.write("                                             PLANNER</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <td align=\"center\"><a href=\"#\" id=\"myWriting\"\r\n");
      out.write("                                          onclick=\"javascript:show()\">내가 작성한 글</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <td align=\"center\"><a href=\"#\" id=\"myBookmark\">북마크</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                 </table></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                     </td>\r\n");
      out.write("\r\n");
      out.write("                     <td width=\"500\">\r\n");
      out.write("                     <table border=\"1\" width=\"580\" height=\"560\" >\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td>\r\n");
      out.write("                                 <div id=\"mypageContent\">\r\n");
      out.write("                                 ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </td>\r\n");
      out.write("\r\n");
      out.write("                           </tr>\r\n");
      out.write("                        </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /test.jsp(95,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("dto");
      // /test.jsp(95,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /test.jsp(169,33) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("plan");
      // /test.jsp(169,33) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${planList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                       <table border=\"1\" cellspacing=\"0\" height=\"200\" width=\"300\">\r\n");
            out.write("                                          <tr>\r\n");
            out.write("                                             <td height=\"140\" align=\"center\"><img\r\n");
            out.write("                                                src=\"img/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plan.coverimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" height=\"140\"></a></td>\r\n");
            out.write("                                          </tr>\r\n");
            out.write("                                          <tr>\r\n");
            out.write("                                             <td align=\"center\"><a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plan.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a><br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plan.writedate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("<br>좋아요\r\n");
            out.write("                                                /");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plan.readnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" </td>\r\n");
            out.write("                                          </tr>\r\n");
            out.write("                                       </table>\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
